baselayout/group

the rkt group is the default group for the /var/lib/rkt directory
Before:
sudo ./rkt install
install: error looking up rkt gid: "rkt" group not found
After
sudo ./rkt install
rkt directory structure successfully created.

baselayout: add the rkt group

---

tmpfiles.d/baselayout-home.conf
tmpfiles.d/baselayout.conf

/home and /home/core creation were both part of baselayout-home.conf,
this poses a problem for initrd usage of systemd-tmpfiles due to how
`systemd-tmpfiles --root` is implemented; it's not performing an actual
chroot, it instead simply prefixes the --root parameter to the paths.
This is arguably a bug in `systemd-tmpfiles --root`, which we may need to
fix in the future.  The core user and group are needed for creating the
/home/core entries with the correct ownership, and they only exist in
/sysroot, not / of the initrd.  As a result systemd-tmpfiles will fail in
creating the /home/core/* entries, even if the core user and group exist in
/sysroot/etc/{passwd,group}, because --root doesn't result in an actual
chroot to /sysroot before attempting to resolve user and group names.
With …

baselayout: move /home creation to baselayout.conf

---

scripts/coreos-tmpfiles

rkt reads /etc/group directly, also users need to be able to easily add
users to the rkt group which requires it to be in /etc.

coreos-tmpfiles: copy rkt group to /etc/group

---

tmpfiles.d/baselayout.conf

systemd takes care of home and srv in systemd/tmpfiles.d/home.conf
fixes coreos/bugs#1158

tmpfiles.d/baselayout.conf: remove home and srv

---

baselayout/group

Fixes bug when `systemd-journal-upload` is unable to read system logs
relates to https://github.com/coreos/bugs/issues/962

Added systemd-journal-upload into systemd-journal group

---

scripts/coreos-tmpfiles.service

if systemd-sysusers is executed before coreos-tmpfiles, coreos-tmpfiles
will not copy users into /etc/passwd, resulting in a core user which is
unmodifiable because it only exists in /usr/share/baselayout/passwd.

scripts: run coreos-tmpfiles after systemd-sysusers

---

scripts/coreos-tmpfiles.service

with After=local-fs.target there's a dep cycle.
[    6.600188] systemd[1]: local-fs.target: Found ordering cycle on local-fs.target/start
[    6.611187] systemd[1]: local-fs.target: Found dependency on local-fs-pre.target/start
[    6.622190] systemd[1]: local-fs.target: Found dependency on systemd-tmpfiles-setup-dev.service/start
[    6.633186] systemd[1]: local-fs.target: Found dependency on systemd-sysusers.service/start
[    6.644161] systemd[1]: local-fs.target: Found dependency on coreos-tmpfiles.service/start
[    6.664161] systemd[1]: local-fs.target: Found dependency on local-fs.target/start
[    6.675186] systemd[1]: local-fs.target: Breaking ordering cycle by deleting job local-fs-pre.target/start
[    6.686187] systemd[1]: local-fs-pre.target: Job local-fs-pre.target/start …

scripts: do not run coreos-tmpfiles.service after local-fs.target

---

baselayout/nsswitch.conf

Now we're shipping sssd we can turn on sss in nsswitch.conf by default. This
will do nothing unless sssd is configured and enabled, but simplifies local
configuration.

Enable sss in nsswitch.conf by default

---

baselayout/passwd

Operator isn't used in CoreOS, so remove the login shell

baselayout: Remove operator's shell

---

tmpfiles.d/baselayout-etc.conf

Thus far we have depended on glibc's nss mechanism to read configuration
from both /etc and /usr so system provided configuration did not need to
exist in the user controlled /etc. In the case of /etc/hosts this has
lead to many problems because 'localhost' must always be resolvable but
often applications use custom resolvers or containers bind mount
/etc/hosts but not the system provided copy under /usr.
For compatibility with existing systems that may have created /etc/hosts
with custom entries but do not include localhost nsswitch.conf must
continue to read from the /usr copy of hosts as well.
Fixes https://github.com/coreos/bugs/issues/1260

tmpfiles: create /etc/hosts if it does not exist

---

Makefile
pam.d/login
pam.d/other
pam.d/passwd
pam.d/su
pam.d/system-auth
pam.d/system-local-login
pam.d/system-login
pam.d/system-remote-login
pam.d/system-services

Gentoo's pambase uses a lot of ifdef magic to support toggling use flags. For the most part we do not need such a dynamic package and it risks subtle compatibility issues in the future. Instead check in the plain ol files directly. pambase will become a stub ebuild for compatibility with portage-stable but otherwise won't be used.

Move pambase to baselayout

---

tmpfiles.d/baselayout-etc.conf
tmpfiles.d/baselayout-hosts.conf

Copy rules are always use the given absolute path, regardless of --root.
This means that when baselayout-etc.conf is executed in the initrd it
fails because /usr/share/baselayout is not included in the initrd. Move
the copy rule to a new config that does not get executed so early.

tmpfiles: move copy rule to new config

---

pam.d/su

We don't want to restrict su to members of the wheel group, so remove this from
the configuration.

Remove pam_wheel.so from su PAM configuration

---

pam.d/system-auth

sssd has support for whitelisting or blacklisting users and groups. To do
so, pam_sss must be able to block login, which means it has to be listed as
required in the account section of sys-auth. The ignore_unknown_user and
ignore_authinfo_unavail mean that it will not block logins if the user is
unknown by sssd or if pam_sss is unable to communicate with sssd.

baselayout: Allow pam_sss to reject users

---

pam.d/systemd-user

pam.d: add the systemd-user service from upstream

---

pam.d/systemd-user

This is really just Gentoo's `233-systemd-user-pam.patch`.  A change from our point of view is that this gives new kernel keyrings to new user sessions.

pam.d: sync systemd-user with v233

---

systemd/resolved.conf.d/50-no-dns-listener.conf

This shouldn't be merged until after coreos/systemd#69.

systemd: disable resolved's stub listener for v232

---

baselayout/nsswitch.conf

This modules ensures that `hostname -s` and `hostname -i` will always
return something.
It's prioritized last so any existing hostname configuration (e.g. in
/etc/hosts) will still work correctly.
This configuration is similar to what most distributions do.
See https://github.com/coreos/bugs/issues/1764

nsswitch: use nss-myhostname

---

modprobe.d/bond.conf

Needed for Packet, and probably useful in general.

modprobe.d: don't automatically create bond0 upon bonding driver load

---

baselayout/coreos-profile.sh

This coordinator conf file is being introduced in locksmith and the
Container Linux Update Operator.
This allows the profile to correctly display information about the
update strategy regardless whether it's being managed by locksmithd or
cluo.
See https://github.com/coreos/container-linux-update-operator/issues/88
Depends on https://github.com/coreos/locksmith/pull/127 being shipped along with this change

coreos-profile: Show update status using conf file

---

baselayout/group
baselayout/nsswitch.conf
baselayout/passwd

This supports resolving dynamic users, which systemd 236 uses by default for some of its services.

baselayout/nsswitch.conf: Use nss-systemd for passwd/group

---

modprobe.d/rbd.conf

The default changed in torvalds/linux@3cfa3b16dd2f1787f9d19d6da2fe9652d806b387 so that `/sys/bus/rbd/add` no longer works.  Since Container Linux does not include the userspace utilities which previously set the option to its new default, users might depend on the old behavior.

modprobe.d: Preserve the pre-4.15 rbd module behavior
